name: "Pull Request Labeler"
on:
  pull_request_target:
  push:
    branches:
      - main
      - dev

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
